export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const POST_CHANNEL = "POST_CHANNEL";
export const FETCH_CHANNELS = "FETCH_CHANNELS ";
export const FETCH_MESSAGES = "FETCH_MESSAGES ";
export const POST_MESSAGES = "POST_MESSAGES ";
export const FETCH_MESSAGES_TS = "FETCH_MESSAGES_TS";
export const CURRENT_CHANNEL = " CURRENT_CHANNEL";
